### ISSUE TITLE
Retos Python Study Group

### ISSUE THREAD

**Issue by jevillanueva** [Gabriel8608/PSG_example-Gabriel-Monta-o#1]
Hola!

Veo que aun faltan retos del python study group....  
Me gustaria invitarte a que continues 😄 
Aquí encontrarás todas las sesiones y sus retos  https://study.pylapaz.org/
No te desanimes!! estare atento a tus retos, animo!!! 

--- 
Feedback:
Hiciste muy buen trabajo con los retos de la sesión 01
Tambien siguen disponibles los retos de la sesión 2 al 11
No te rindas, estare aqui esperando tu codigo :D si tienes alguna duda esta el grupo de whatsapp para preguntan o puedes usar este thread para consultar que yo lo leeré!

Sigue adelante!

> Los desafíos son lo que hacen la vida interesante, y superarlos es lo que hace la vida significativa. - Joshua J. Marine

**Comment by Gabriel8608** [comment]
Hola, quetal. Las últimas semanas tenía muchas cossas que hacer y andaba bastante desganado y cansado de tantos asuntos.

Ahora que estoy mas libre además de las prontas vacaciones, estoy haciendo los retos y viendo las sesiones.

[Estoy subiendo los retos a este repositorio, por si quieres checarlos:](https://github.com/Gabriel8608/python-study-group.git)

Ya conseguí usar marcdown, y encontré un canal de youtuve donde explican como usar VS code con mi lector de pantalla, NVDA.

Gracias por todo. Estoy bastante entusiasmado por esto, asique boy a ponerle mi máximo empeño.

> Algo tarde, pero es mejor tarde que nunca. Dijo un compañero del colegio.
